spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripocket-db
    username: tripocket-user
    password: admin
server:
  servlet:
    context-path: /api

keycloak:
  admin:
    client-secret: dev-secret